#!/usr/bin/env bash
# Regenerate per-IP bootstrap SQL from the structural migrations.
# Concatenates the structural migrations (Beaver Lodge story seeds excluded)
# and word-boundary-swaps the `cyoa` schema token for each target schema.
# Run from the repo root:  bash scripts/build_bootstrap.sh
set -euo pipefail
MIG=supabase/migrations
OUT=supabase/bootstrap
mkdir -p "$OUT"

# Structural migrations in dependency order.
# Intentionally excluded (Nibbles-specific story content):
#   *_seed_beaver_lodge.sql, *_seed_forbidden.sql, *_seed_prologue_lore.sql
FILES=(
  20260414085348_init.sql
  20260414104036_grants.sql
  20260414104703_fix_rls_recursion.sql
  20260414200246_sessions.sql
  20260415194607_default_episode.sql
  20260415215054_pages_facts_used.sql
  20260415223115_canon_reconciliation.sql
  20260420100000_chapters.sql
  20260420110000_chapter_lore_text.sql
)

build () {
  local schema=$1 ip=$2 outfile=$3
  {
    echo "-- =============================================================="
    echo "-- CYOA bootstrap for: ${ip}"
    echo "-- Schema: ${schema}  (in the shared RIVALS Supabase project)"
    echo "-- Generated by scripts/build_bootstrap.sh. Placeholder seeds only."
    echo "-- Run once in the Supabase SQL editor, then:"
    echo "--   Settings -> API -> Exposed schemas -> add '${schema}'"
    echo "--   then run:  notify pgrst, 'reload schema';"
    echo "-- =============================================================="
    echo
    for f in "${FILES[@]}"; do
      echo "-- ----- from ${f} -----"
      perl -pe 's/\bcyoa\b/'"${schema}"'/g' "${MIG}/${f}"
      echo
    done
  } > "${OUT}/${outfile}"
  echo "wrote ${OUT}/${outfile}"
}

build cyoa_rex    "Tribe Called Rex" cyoa_rex.sql
build cyoa_gorgez "Drop Ded Gorgez"  cyoa_gorgez.sql
